permalink: pretty
markdown: kramdown

title: "Jordan West's Blog"
description: 'Software Engineer. Interest in artificial intelligence and how things learn. Avatar art by <a href="http://twitter.com/scribjellyfish">@scribjellyfish</a>'
paginate: 5
excerpt_separator: '<!--more-->'

author:
  name: Jordan West
  github: jordan-west

github:
    repo: https://github.com/jordan-west/jordan-west.github.io

version: 1.0.0

plugins:
    - jekyll-paginate
