permalink: pretty
markdown: kramdown

title: "Jordan West's Blog"
description: 'Computer Science graduate. Interest in artificial intelligence and how things learn. Avatar art by <a href="http://twitter.com/scribjellyfish">@scribjellyfish</a>'
paginate: 5
excerpt_separator: '<!--more-->'

author:
  name: Jordan West
  github: jordanlwest
  google_analytics_id: UA-110403942-1
  google_analytics_url: jordanlwest.github.io

version: 1.0.0

plugins:
    - jekyll-paginate
